import mongoose from 'mongoose';

export interface IOrder {
  _id: string;
  orderId: string;
  customerInfo: {
    name: string;
    phone: string;
    email: string;
  };
  orderType: 'file' | 'template';
  fileURL?: string; // Legacy: single file URL (for backward compatibility)
  fileURLs?: string[]; // Array of file URLs for multiple files
  fileType?: string; // Store the original file type (e.g., 'application/pdf', 'image/jpeg') - Legacy support
  fileTypes?: string[]; // Array of file types for multiple files (MIME types)
  originalFileName?: string; // Store the original file name
  originalFileNames?: string[]; // Array of original file names for multiple files
  // Template-specific fields
  templateId?: string;
  templateName?: string;
  formData?: Record<string, string | number | boolean>;
  filledDocxUrl?: string;
  filledPdfUrl?: string;
  // Legacy template data for backward compatibility
  templateData?: {
    templateType: string;
    formData: Record<string, string | number | boolean>;
    generatedPDF?: string;
  };
  printingOptions: {
    pageSize: 'A4' | 'A3';
    color: 'color' | 'bw' | 'mixed';
    sided: 'single' | 'double';
    copies: number;
    pageCount?: number;
    serviceOption?: 'binding' | 'file' | 'service'; // Legacy support
    serviceOptions?: ('binding' | 'file' | 'service')[]; // Per-file service options
    pageColors?: {
      colorPages: number[]; // Array of page numbers that should be printed in color
      bwPages: number[];    // Array of page numbers that should be printed in B&W
    } | Array<{ // Per-file page colors (new format)
      colorPages: number[]; // Array of page numbers that should be printed in color
      bwPages: number[];    // Array of page numbers that should be printed in B&W
    }>;
    fileOptions?: Array<{ // Per-file printing options (new format)
      pageSize: 'A4' | 'A3';
      color: 'color' | 'bw' | 'mixed';
      sided: 'single' | 'double';
      copies: number;
      pageColors?: {
        colorPages: number[];
        bwPages: number[];
      };
    }>;
  };
  paymentStatus: 'pending' | 'completed' | 'failed';
  orderStatus: 'pending' | 'processing' | 'printing' | 'printed' | 'ready_for_pickup' | 'dispatched' | 'delivered' | 'completed';
  status: 'pending_payment' | 'paid' | 'processing' | 'printing' | 'printed' | 'ready_for_pickup' | 'dispatched' | 'delivered' | 'completed' | 'cancelled' | 'refunded';
  amount: number;
  deliveryOption: {
    type: 'pickup' | 'delivery';
    location?: {
      lat: number;
      lng: number;
      address: string;
    };
    distance?: number;
    deliveryCharge?: number;
    address?: string;
    city?: string;
    state?: string;
    pinCode?: string;
    landmark?: string;
    flatBuilding?: string;
    recipientName?: string;
    recipientPhone?: string;
    pickupLocationId?: string;
    partnerId?: string;
    partnerDeliveryPoint?: string;
    pickupLocation?: {
      _id: string;
      name: string;
      address: string;
      lat: number;
      lng: number;
      contactPerson?: string;
      contactPhone?: string;
      operatingHours?: string;
      gmapLink?: string;
    };
  };
  razorpayOrderId?: string;
  razorpayPaymentId?: string;
  // Monetization split for paid templates
  templatePrice?: number; // Price charged for using the template (if any)
  templateCommissionPercent?: number; // Website share percentage at time of order
  creatorShareAmount?: number; // Amount to be paid out to creator (INR)
  platformShareAmount?: number; // Platform earnings for this order (INR)
  templateCreatorUserId?: string; // Reference to template creator user ID (string for simplicity)
  expectedDate?: Date;
  deliveryNumber?: string; // Format: {LETTER}{YYYYMMDD}{PRINTER_INDEX}
  printedAt?: Date; // When printing was completed
  // Shiprocket delivery tracking fields
  shiprocket?: {
    orderId?: number;        // Shiprocket's order ID
    shipmentId?: number;     // Shiprocket's shipment ID
    awbCode?: string;        // Tracking number (Air Waybill)
    courierName?: string;    // Assigned courier name
    trackingUrl?: string;    // Direct tracking URL
    status?: string;         // Latest Shiprocket status string
    lastTrackedAt?: Date;    // When we last fetched tracking info
  };
  // QR dispatch verification fields
  verificationOtp?: string;       // 6-digit OTP for dispatch verification
  otpExpiresAt?: Date;            // OTP expiry time
  deliveryVerifiedAt?: Date;      // When delivery was verified/confirmed
  deliveryVerifiedBy?: string;    // Email of person who verified delivery
  partnerId?: string;             // Reference to the Partner handling this order
  createdAt: Date;
  updatedAt: Date;
}

const orderSchema = new mongoose.Schema<IOrder>({
  orderId: {
    type: String,
    required: false, // Will be auto-generated by pre-save hook
    unique: true,
    index: true,
  },
  customerInfo: {
    name: { type: String, required: true },
    phone: { type: String, required: true },
    email: { type: String, required: true },
  },
  orderType: {
    type: String,
    enum: ['file', 'template'],
    required: true,
  },
  fileURL: String, // Legacy: single file URL (for backward compatibility)
  fileURLs: [String], // Array of file URLs for multiple files
  fileType: String, // Legacy support
  fileTypes: [String], // Array of file types for multiple files (MIME types)
  originalFileName: String, // Legacy: single file name (for backward compatibility)
  originalFileNames: [String], // Array of original file names for multiple files
  // Template-specific fields
  templateId: String,
  templateName: String,
  formData: mongoose.Schema.Types.Mixed,
  filledDocxUrl: String,
  filledPdfUrl: String,
  // Legacy template data for backward compatibility
  templateData: {
    templateType: String,
    formData: mongoose.Schema.Types.Mixed,
    generatedPDF: String,
  },
  printingOptions: {
    pageSize: {
      type: String,
      enum: ['A4', 'A3'],
      required: true,
    },
    color: {
      type: String,
      enum: ['color', 'bw', 'mixed'],
      required: true,
    },
    sided: {
      type: String,
      enum: ['single', 'double'],
      required: true,
    },
    copies: {
      type: Number,
      required: true,
      min: 1,
    },
    pageCount: {
      type: Number,
      default: 1,
    },
    serviceOption: {
      type: String,
      enum: ['binding', 'file', 'service'],
    },
    serviceOptions: {
      type: [String],
      enum: ['binding', 'file', 'service'],
    },
    pageColors: {
      type: mongoose.Schema.Types.Mixed, // Support both single object and array format
      // Can be:
      // 1. Single object: { colorPages: [Number], bwPages: [Number] } (legacy)
      // 2. Array: [{ colorPages: [Number], bwPages: [Number] }, ...] (per-file)
    },
    fileOptions: {
      type: mongoose.Schema.Types.Mixed, // Per-file printing options array
      // Array of objects: [{ pageSize, color, sided, copies, pageColors? }, ...]
    },
  },
  paymentStatus: {
    type: String,
    enum: ['pending', 'completed', 'failed'],
    default: 'pending',
  },
  orderStatus: {
    type: String,
    enum: ['pending', 'processing', 'printing', 'printed', 'ready_for_pickup', 'dispatched', 'delivered', 'completed'],
    default: 'pending',
  },
  status: {
    type: String,
    enum: ['pending_payment', 'paid', 'processing', 'printing', 'printed', 'ready_for_pickup', 'dispatched', 'delivered', 'completed', 'cancelled', 'refunded'],
    default: 'pending_payment',
  },
  amount: {
    type: Number,
    required: true,
  },
  deliveryOption: {
    type: {
      type: String,
      enum: ['pickup', 'delivery'],
      required: true,
      default: 'pickup'
    },
    pickupLocationId: String,
    partnerId: String,
    partnerDeliveryPoint: String,
    pickupLocation: {
      _id: String,
      name: String,
      address: String,
      lat: Number,
      lng: Number,
      contactPerson: String,
      contactPhone: String,
      operatingHours: String,
      gmapLink: String
    },
    location: {
      lat: Number,
      lng: Number,
      address: String
    },
    distance: Number,
    deliveryCharge: Number,
    address: String,
    city: String,
    state: String,
    pinCode: String,
    landmark: String,
    flatBuilding: String,
    recipientName: String,
    recipientPhone: String
  },
  razorpayOrderId: String,
  razorpayPaymentId: String,
  templatePrice: {
    type: Number,
    required: false,
    min: 0,
  },
  templateCommissionPercent: {
    type: Number,
    required: false,
    min: 0,
    max: 50,
  },
  creatorShareAmount: {
    type: Number,
    required: false,
    min: 0,
  },
  platformShareAmount: {
    type: Number,
    required: false,
    min: 0,
  },
  templateCreatorUserId: {
    type: String,
    required: false,
  },
  expectedDate: {
    type: Date,
    validate: {
      validator: function (value: Date) {
        if (!value) return true; // Optional field
        const today = new Date();
        today.setHours(0, 0, 0, 0); // Reset time to start of day
        return value >= today; // Must be today or later
      },
      message: 'Expected delivery date must be today or later'
    }
  },
  deliveryNumber: String, // Format: {LETTER}{YYYYMMDD}{PRINTER_INDEX}
  printedAt: Date, // When printing was completed
  // Shiprocket delivery tracking
  shiprocket: {
    orderId: Number,
    shipmentId: Number,
    awbCode: String,
    courierName: String,
    trackingUrl: String,
    status: String,
    lastTrackedAt: Date,
  },
  // QR dispatch verification
  verificationOtp: String,
  otpExpiresAt: Date,
  deliveryVerifiedAt: Date,
  deliveryVerifiedBy: String,
  partnerId: {
    type: String,
    required: false,
    index: true
  },
}, {
  timestamps: true,
});

// Generate order ID before saving
orderSchema.pre('save', async function () {
  if (this.isNew && !this.orderId) {
    let attempts = 0;
    const maxAttempts = 10;

    while (attempts < maxAttempts) {
      try {
        // Use timestamp + random number for better uniqueness
        const timestamp = Date.now().toString().slice(-6);
        const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
        const candidateOrderId = `ORD${timestamp}${random}`;

        // Check if this orderId already exists
        const existingOrder = await mongoose.model('Order').findOne({ orderId: candidateOrderId });

        if (!existingOrder) {
          this.orderId = candidateOrderId;
          break;
        }

        attempts++;
      } catch (error) {
        console.error('Error generating order ID:', error);
        attempts++;
      }
    }

    // Fallback to UUID if all attempts fail
    if (!this.orderId) {
      const { v4: uuidv4 } = await import('uuid');
      this.orderId = `ORD${uuidv4().replace(/-/g, '').substring(0, 10).toUpperCase()}`;
    }
  }
});

export default mongoose.models.Order || mongoose.model<IOrder>('Order', orderSchema);
